name: HealPlugin
version: '1.0-SNAPSHOT'
main: org.plugin.minecraft_plugin.Heal
api-version: '1.21'
commands:
  heal:
    description: Ulecz się do pełnego zdrowia
    usage: /heal
  randomeffect:
    description: Losowy efekt
    usage: /randomeffect