name: Minecraft_plugin
version: '1.0-SNAPSHOT'
main: org.plugin.minecraft_plugin.Minecraft_plugin
api-version: '1.21'

commands:
  tpa:
    description: witam witam
  tpaaccept:
    description: witam witam 123
  heal:
    description: Ulecz się do pełnego zdrowia
    usage: /heal
  randomeffect:
    description: Losowy efekt
    usage: /randomeffect
  sethome:
    description: Set location of your home
  home:
    description: Takes you to your home
  seeinventory:
    description: Admin command to see someone's inventory
  enderchest:
    description: Admin command to see someone's enderchest
