name: minecraft_plugin
version: '1.0-SNAPSHOT'
main: org.plugin.minecraft_plugin.Minecraft_plugin
api-version: '1.21'
commands:
  sethome:
    description: Set location of your home
  home:
    description: Takes you to your home
